export type IconType =
  | 'check'
  | 'chevronDown'
  | 'chevronLeft'
  | 'chevronRight'
  | 'chevronUp'
  | 'close'
  | 'copy'
  | 'docs'
  | 'done'
  | 'edit'
  | 'etherscan'
  | 'hamburger'
  | 'info'
  | 'link'
  | 'outlink'
  | 'planetariumHorizontal'
  | 'planetariumSymbol'
  | 'planetariumVertical'
  | 'planetariumWordmark'
  | 'slideClose'
  | 'time'
  | 'transfer'
  | 'warning'

export type IconSize = 12 | 16 | 24 | 32 | 40
